[[headers]]
  for = "/*"
  [headers.values]
    SameSite = "Lax"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' *.netlify.app netlify.app googletagmanager.com *.googletagmanager.com; worker-src 'self' blob: data: lr-ingest.io *.lr-ingest.io; prefetch-src 'self'; connect-src 'self' *.netlify.app netlify.app google-analytics.com *.google-analytics.com; img-src 'self'; font-src 'unsafe-inline' gstatic.com *.gstatic.com; manifest-src 'self'; style-src 'unsafe-inline' googleapis.com *.googleapis.com; frame-ancestors 'self'; form-action 'self'; script-src-elem 'self' 'unsafe-inline' googletagmanager.com *.googletagmanager.com"
