backend:
  name: github
  branch: master # Branch where CMS changes will be committed
  repo: Bright-Path/brightpath.github.io # Path to your GitLab repository
media_folder: "src/upload" # Media files will be stored in the repo under images/uploads
public_folder: "/upload"

collections:
  - name: "page"
    label: "Pages"
    create: false
    identifier_field: name
    folder: "src/content/page"
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "Featured Image"
        name: "hero"
        widget: "image"
        required: false
      - label: "Featured Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Feature Description"
        name: "description"
        widget: "markdown"
        required: false
      - label: "Additional Content"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "page"
  - name: "beers"
    label: "Beers"
    folder: "src/content/beer"
    identifier_field: name
    create: true
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "ABV"
        name: "abv"
        widget: "string"
        required: false
      - label: "Short Description"
        name: "description"
        widget: "text"
        required: false
      - label: "Available on Tap"
        name: "tap"
        widget: "boolean"
        default: false
      - label: "Tap location"
        name: "tap_loc"
        widget: "number"
        default: false
      - label: "Available in Cans"
        name: "canned"
        widget: "boolean"
        default: false
      - label: "Long Description"
        name: "page_description"
        widget: "markdown"
        required: false
      - label: "Logo"
        name: "logo"
        widget: "image"
        required: false
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        fields:
        - name: "image"
          label: "Image"
          widget: "image"
          required: true
        - name: "alt"
          label: "Description"
          widget: "markdown"
          required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "beer"
  - name: "locations"
    label: "Locations"
    folder: "src/content/locations"
    create: true
    identifier_field: name
    fields:
      - name: "name"
        widget: "string"
        required: true
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
      - label: "Street Address"
        name: "address"
        widget: "string"
        description: "123 Fake St"
        required: true
      - label: "City, State, Zip"
        name: "address2"
        widget: "string"
        description: "Jim Thorpe, PA 18229"
        required: true
      - label: "Map link"
        name: "mapLink"
        widget: "string"
        required: false
      - label: "Phone Number"
        name: "phone"
        widget: "string"
        description: "specific to this location"
        required: false
      - label: "Email"
        name: "email"
        widget: "string"
        description: "specific to this location"
        required: false
      - label: "Hours"
        name: "hours"
        widget: "list"
        required: false
        fields:
          - label: "Day"
            name: "day"
            widget: "string"
            required: true
          - label: "Hours"
            name: "hours"
            widget: "string"
            required: true
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "locations"
  - name: "info"
    label: "Brewery Information and Website Configuration"
    folder: "src/content/info"
    identifier_field: name
    fields:
      - name: "name"
        label: "Brewery Name"
        widget: "string"
        required: true
      - label: "Site Header and Navigation"
        name: "header"
        widget: "object"
        summary: "Configuration of the Header and Navigation Bar"
        fields:
        - label: "Nav Logo"
          name: "logo"
          widget: "image"
          required: true
        - label: "Nav Secondary Logo"
          name: "logo_text"
          widget: "image"
          required: true
        - label: "Show 'Home' in Navigation?"
          name: "showHome"
          widget: "boolean"
          default: true
        - label: "Site Navigation"
          name: "nav"
          widget: "list"
          required: false
          fields:
            - label: "Page Name"
              name: "link_text"
              widget: "string"
              required: true
            - label: "URL"
              name: "url"
              widget: "string"
              required: true
            - label: "External Link"
              name: "external"
              widget: "boolean"
              default: false
      - label: "Site Announcement"
        name: "alert"
        widget: "object"
        summary: "Announcement displayed in banner on every page"
        fields:
        - label: "Message"
          name: "message"
          widget: "markdown"
          required: false
        - label: "Show Message"
          name: "display"
          widget: "boolean"
          default: false
      - label: "Main Logo"
        name: "logo"
        widget: "image"
        description: "The main logo of the brewery - not used in the header"
        required: false
      - label: "Street Address"
        name: "address"
        widget: "string"
        description: "123 Fake St"
        required: true
      - label: "City, State Zip"
        name: "address2"
        widget: "string"
        description: "Jim Thorpe, PA 18229"
        required: true
      - label: "Phone Number"
        name: "phone"
        widget: "string"
        required: false
      - label: "Email"
        name: "email"
        widget: "string"
        required: false
      - label: "Social Media"
        name: "social"
        widget: "list"
        required: false
        fields:
          - label: "Platform"
            name: "platform"
            widget: "string"
            required: true
          - label: "Handle"
            name: "handle"
            widget: "string"
            required: true
          - label: "URL"
            name: "url"
            widget: "string"
            required: true
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "info"
  - name: "privacy"
    label: "Privacy Policy"
    folder: "src/content/privacy"
    identifier_field: name
    fields:
      - name: "name"
        label: "Page Name"
        widget: "string"
        required: true
      - label: "Page Content"
        name: "content"
        widget: "markdown"
        required: false
      - label: "Featured Image"
        name: "hero"
        widget: "image"
        required: false
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "privacy"
